### ISSUE TITLE
Auth.currentAuthenticatedUser() does not return a user after redirect?

### ISSUE THREAD

**Issue by fireflysemantics** [mlabieniec/AngularMaterialPWA#13]
Hi,

Thanks for creating the article and the awesome demo.  I'm noticing that `Auth.getCurrentAuthenticatedUser()` and `Auth.getSession()` do not return responses right after redirect.

I've described the issue more here:
https://stackoverflow.com/questions/60436826/what-authentication-check-using-the-auth-api-should-we-perform-in-our-angular-au

Thoughts?

**Comment by mlabieniec** [comment]
@fireflysemantics seems like your solution in your post there is the right approach depending on when you are wanting to access the user/session, using `Hub.listen` will allow you to catch the session/logged in user when they are populated.  See example here: https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui
