### ISSUE TITLE
searchText missing

### ISSUE THREAD

**Issue by morrnel** [mlabieniec/AngularMaterialPWA#2]
Is there a disconnect between the filter pipe and country code select? Perhaps I missed something.

ERROR in src\app\auth\country-code-select\country-code-select.component.html(2,21): : Property 'searchText' does not exist on type 'CountryCodeSelectComponent'.
src\app\auth\country-code-select\country-code-select.component.html(5,22): : Property 'searchText' does not exist on type 'CountryCodeSelectComponent'.
src\app\auth\country-code-select\country-code-select.component.html(2,21): : Property 'searchText' does not exist on type 'CountryCodeSelectComponent'.

good article
mn

**Comment by dankibler** [comment]
I had the same error. I got past it by changing "searchText" to "selectCountry", but since the selector does not seem to work, that probably isn't correct.

**Comment by dankibler** [comment]
Michael - thanks for this comprehensive sample app. Most things are working, but I'm having a problem with the avatar image upload. I'm getting a 403 error on Storage.put(). The bucket exists and has full permissions for the root account. Is this a Cognito problem? Where should I look to find the problem?

Thanks
Dan

**Comment by jamesmbull** [comment]
Modifying **tsconfig.json** with the below fixed the issue for me. I have no idea what I'm doing so this may have other repercussions! 

`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    **//"target": "es2015", // Fix bug with amplify and angular 8
    // https://github.com/aws-amplify/amplify-js/issues/3193
    "target": "es5",**
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}`

**Comment by dankibler** [comment]
I now have this working. I think the instructions omitted the step to add the code from GitHub to filter.pipe.ts. When I looked, it had the default code.

**Comment by dankibler** [comment]
I also added  
searchText: string; 
to CountryCodeSelectComponent

**Comment by jamesmbull** [comment]
I followed similar steps but kept running into errors. I'll drop my version info below in case it's of any interest to the next person.

'''
Angular CLI: 8.1.2
Node: 11.15.0
OS: linux x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cdk                      8.1.1
@angular/material                 8.1.1
@angular/pwa                      0.801.2
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
'''
