### ISSUE TITLE
Auth component is blank

### ISSUE THREAD

**Issue by daghanacay** [mlabieniec/AngularMaterialPWA#6]
Please add 

this._router.navigate(['/auth/signin']);

at the ngOnInit method of auth,component.ts

**Comment by mlabieniec** [comment]
@daghanacay the main landing component is intentionally blank to allow customization of the flow. I didn't add any redirects there intentionally so this can be used to customize the flow to the users desire here. Perhaps I can add more of a landing page here with links to each for now so it's not confusing.
